# COPYRIGHT Dassault Systemes 2022
#======================================================================
# Imakefile for module TRAUtilitiesMod.m
#======================================================================
#
#  Aug 2022  Creation: Code generated by the CAA wizard  Naga
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP \
            CATObjectModelerBase \
            CATObjectSpecsModeler  \
            CATMecModInterfaces \
            CATInteractiveInterfaces \
            CATMechanicalCommands \
            CATApplicationFrame \
            CATMechanicalModeler  \
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
