// COPYRIGHT Dassault Systemes 2022
//===================================================================
//
// TRACmdAddin.h
// Provide implementation to interface
//    CATIPrtCfgAddin
//    CATIShapeDesignWorkshopAddin

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	TRAECmdAddin
//EXTENSIONTYPE:	DataExtension

//    TIE: CATIPrtCfgAddin
//    TIE: CATIShapeDesignWorkshopAddin

//End CAA2 Wizard Generation Report
//
//  Aug 2022  Creation: Code generated by the CAA wizard  Naga
//===================================================================
#ifndef TRACmdAddin_H
#define TRACmdAddin_H

#include "CATBaseUnknown.h"
#include "CATCmdContainer.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATIPrtCfgAddin
*  <li>@href CATIShapeDesignWorkshopAddin
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class TRACmdAddin: public CATBaseUnknown

{
  CATDeclareClass;

  public:

	  void CreateCommands();
	  CATCmdContainer * CreateToolbars();

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     TRACmdAddin ();
     virtual ~TRACmdAddin ();


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  TRACmdAddin (TRACmdAddin &);
  TRACmdAddin& operator=(TRACmdAddin&);

};

//-----------------------------------------------------------------------

#endif
