// COPYRIGHT Dassault Systemes 2022
//===================================================================
//
// TRAStCommand8.h
// The state chart based command: TRAStCommand8
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  Aug 2022  Creation: Code generated by the CAA wizard  Naga
//===================================================================
#ifndef TRAStCommand8_H
#define TRAStCommand8_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "CATPathElementAgent.h"


class CATIndicationAgent;

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class TRAStCommand8: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( TRAStCommand8, CATStateCommand )

  public:

  TRAStCommand8();
  virtual ~TRAStCommand8();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
  virtual void     BuildGraph();

   // Creates the center-line
  // =======================
  boolean CreateCtrLine(void* iData=NULL);

 

  

  private:

  // The selection agent
  // -------------------
  CATPathElementAgent          *_pObjectAgent;
};

//----------------------------------------------------------------------

#endif
