// COPYRIGHT Dassault Systemes 2022
//===================================================================
//
// TRAStCommand9.h
// The state chart based command: TRAStCommand9
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  Aug 2022  Creation: Code generated by the CAA wizard  Naga
//===================================================================
#ifndef TRAStCommand9_H
#define TRAStCommand9_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "CATPathElementAgent.h"


class CATIndicationAgent;

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class TRAStCommand9: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( TRAStCommand9, CATStateCommand )

  public:

  TRAStCommand9();
  virtual ~TRAStCommand9();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
  virtual void     BuildGraph();

    /**
     * Action associated to state transitions.
     */
  boolean DressUp(void * data);

  private:

  // The selection agent
  // -------------------
  CATPathElementAgent          *_pObjectAgent;
};

//----------------------------------------------------------------------

#endif
