// COPYRIGHT Dassault Systemes 2022
//===================================================================
//
// TRAUtilities.h
// Header definition of TRAUtilities
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Aug 2022  Creation: Code generated by the CAA wizard  Naga
//===================================================================
#ifndef TRAUtilities_H
#define TRAUtilities_H

#include "TRAUtilitiesMod.h"
#include "CATBaseUnknown.h"
#include "CATISpecObject.h"
#include "CATIPrtContainer.h"
#include "CATDocument.h"




//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* Do not use the @href TRAUtilities constructor to
* do such and such but instead...
*
* @example
*  // example is optional
*  pObject = new TRAUtilities;
*  pObject->SetXXX(...);
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class ExportedByTRAUtilitiesMod TRAUtilities: public CATBaseUnknown
{
  CATDeclareClass;

  public:

	  HRESULT CAAMcaGetGeometry(CATISpecObject_var ispModelPart, const CATUnicodeString iInputName,
				 CATBaseUnknown ** oInput);

  // Standard constructors and destructors
  // -------------------------------------
     TRAUtilities ();
     virtual ~TRAUtilities ();

  // Copy constructor and equal operator
  // -----------------------------------
  TRAUtilities (TRAUtilities &);
  TRAUtilities& operator=(TRAUtilities&);

  CATIPrtContainer* GetPartContainer();

  CATDocument* GetCurrentDocument();

  HRESULT ObjectUpdate(const CATISpecObject_var & ispSpec);

};

//-----------------------------------------------------------------------

#endif
