# COPYRIGHT Dassault Systemes 2022
#======================================================================
# Imakefile for module TRACmdAddinMod.m
#======================================================================
#
#  Aug 2022  Creation: Code generated by the CAA wizard  Naga
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP \
JS0FM JS0GROUP PartItf PartInterfacesUUID GSMInterfacesUUID \
CATApplicationFrame \
CATGitInterfaces  \
JS0GROUP JS0FM \
            CATObjectModelerBase \
            CATUdfInterfaces \
            CATObjectSpecsModeler  \
            CATMecModInterfaces \
            CATMechanicalModeler \
            CATGeometricObjects \
            CATCGMGeoMath \
            CATConstraintModeler \
            CATConstraintModelerItf \
            CATMechanicalCommands \
            CATVisualization \
            CATViz\
    	    CATInteractiveInterfaces \    	    
            KnowledgeItf \
            CATLiteralFeatures \
            TRAUtilitiesMod \
            JS0CORBA \
            CATDraftingInterfaces \
            CATSketcherInterfaces \
            CATProductStructure1  \
            Drafting2DLItfCPP  \
            CATTPSUUID \
            CATDialogEngine  \
            DI0PANV2 \
            CATMathematics \
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)
            
            

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
