// COPYRIGHT Dassault Systemes 2022
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework TRACmdAddinFW
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Aug 2022  Creation: Code generated by the CAA wizard  Naga
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Protected);
AddPrereqComponent("GSMInterfaces",Protected);
AddPrereqComponent("PartInterfaces",Protected);
AddPrereqComponent("ApplicationFrame",Protected);
AddPrereqComponent("ObjectModelerBase",Public);
AddPrereqComponent("ObjectSpecsModeler",Public);
AddPrereqComponent("Visualization",Public);
AddPrereqComponent("VisualizationBase",Public);
AddPrereqComponent("Mathematics",Protected);
AddPrereqComponent("MecModInterfaces",Public);
AddPrereqComponent("MechanicalModeler",Public);
AddPrereqComponent("MechanicalModelerUI",Public);
AddPrereqComponent("MechanicalCommands",Public);
AddPrereqComponent("LiteralFeatures",Public);
AddPrereqComponent("KnowledgeInterfaces",Public);
AddPrereqComponent("DialogEngine",Protected);
AddPrereqComponent("Dialog",Protected);
AddPrereqComponent("InteractiveInterfaces",Public);
AddPrereqComponent("ComponentsCatalogsInterfaces",Public);
AddPrereqComponent("ConstraintModelerUI",Public);
AddPrereqComponent("ConstraintModeler",Public);
AddPrereqComponent("ConstraintModelerInterfaces",Public);
AddPrereqComponent("GeometricObjects",Public);
AddPrereqComponent("CATTPSInterfaces",Public);
AddPrereqComponent("DraftingInterfaces",Public);
AddPrereqComponent("SketcherInterfaces",Public);
AddPrereqComponent("NewTopologicalObjects",Public);
AddPrereqComponent("ProductStructure",Public);
AddPrereqComponent("InfInterfaces",Public);
AddPrereqComponent("Drafting2DLInterfaces",Public);

// END WIZARD EDITION ZONE
